events {
    worker_connections 1024;
}

http {
    # grupo de balanceo de carga con los nombres de los servicios en Docker
    upstream frontend_servers {
        server front:3000 max_fails=1 fail_timeout=5s;
        server front2:3000 max_fails=1 fail_timeout=5s;
}

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Evita que el navegador cachee para que al recargar alterne de inmediato
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }
    }
}